### ISSUE TITLE
Discussion [RFC]: 培训文档新增内容

### ISSUE THREAD

**Issue by shejialuo** [AIOps-ISET/AIOpsLab_tutorial#8]
根据璐姐的要求，培训文档需要进行修改和新增。主要集中在两个方面：

1. 技术上，璐姐打算往硬件层方面发展，需要学习操作系统、Liunx内核等知识，减少对微服务知识方面的了解。
2. 学术上，璐姐希望打算聚焦于故障检测和根因，这部分需要博士生筛选一些论文入门。

本issue的打开主要是征集意见，我们该如何去完善这个文档呢？所有的后续工作将按照本issue进行划分。

同时，我们希望让研一的同学熟悉这个培训文档的组成结构，所以PULL REQUEST我们会让研一的同学完成。

**Comment by shejialuo** [comment]
@North-C 雨晴你可以说是对Liunx内核了解得最多的了。但是有个问题，Linux内核模块过于多了，我们应该注重介绍哪方面呢？作为一个入门文档而言，我感觉我们更多地应该从入门的角度去思考这个问题？其实操作系统的入门反而我们能提供一些国外的课程或者一些十分优秀的书籍。这个点我觉得可以和璐姐交流一下，哪种程度比较OK呢？

@swhoro 晨屹，你的任务是带研一的同学熟悉如何提交PR，同时我也希望你能提供一些你的想法。

@likeran2234 @kikily-2203 科燃和潇然，你们两的任务是明确需求，“硬件层”具体应该是哪一个方面了，我和雨晴目前不太了解。我们需要明确这个需求。

@YaXiao7 @CalvinHMX 亚晓和明轩，你们两个主要完成学术上的工作，最关键的是你们要去整理好论文。最重要的点还是如何让新人入门，最好是优秀的综述文章和一些在宏观上描述技术的文章。其次是对于这两个方向深入的文章，需要进行讲述。

**Comment by North-C** [comment]
按照现状来看，大部分人应该是缺少对操作系统或者内核方面的深入了解，所以我建议是给出一些入门的资料，先打开进入的大门，做好铺垫比较重要，可以是经典书，公开课，这部分我建议是不要多给资料，选出最合适的一两个就行，关键是能学完看完，后续有自己的鉴别能力再自己挑。

其次，以我们组的项目情况来看，现在还是会要结合运维项目来学，毕竟用到的会多一些，所以eBPF技术当做重要部分进行掌握，既能用到项目里面，后续对于学习内核其他子系统，调试内核都很有帮助。之后如果需要一些硬件和其他内核子系统的内容，就通过给出各个子系统里面的参考资料和路径图，有需要自己去学就好了，重在实际的交流和实践。

基本确定好这部分的结构后我可以先写个初稿，后面去问问璐姐的意见。

**Comment by shejialuo** [comment]
> 按照现状来看，大部分人应该是缺少对操作系统或者内核方面的深入了解，所以我建议是给出一些入门的资料，先打开进入的大门，做好铺垫比较重要，可以是经典书，公开课，这部分我建议是不要多给资料，选出最合适的一两个就行，关键是能学完看完，后续有自己的鉴别能力再自己挑。
> 
> 其次，以我们组的项目情况来看，现在还是会要结合运维项目来学，毕竟用到的会多一些，所以eBPF技术当做重要部分进行掌握，既能用到项目里面，后续对于学习内核其他子系统，调试内核都很有帮助。之后如果需要一些硬件和其他内核子系统的内容，就通过给出各个子系统里面的参考资料和路径图，有需要自己去学就好了，重在实际的交流和实践。
> 
> 基本确定好这部分的结构后我可以先写个初稿，后面去问问璐姐的意见。

确实，本质上还是起到一个入门的作用最为重要了。我也觉得可能eBPF技术是作为引入最好的一点，不是那么地底层，是一个很好的中间桥梁。

**Comment by likeran2234** [comment]
硬件层所表述的是指计算机组成、计算机网络和操作系统的各个方面的知识吗，目前接触项目我觉得对linux系统的一些基本知识和常用命令了解是最有意义的。例如linux系统可以分模块学文件系统、I/O管理、内存管理等。这些我目前学习都是看文章、博客，还没有看书籍/课程系统性地学过。

**Comment by shejialuo** [comment]
> 硬件层所表述的是指计算机组成、计算机网络和操作系统的各个方面的知识吗，目前接触项目我觉得对linux系统的一些基本知识和常用命令了解是最有意义的。例如linux系统可以分模块学文件系统、I/O管理、内存管理等。这些我目前学习都是看文章、博客，还没有看书籍/课程系统性地学过。

主要我也很久没开组会了，我不太能够理解璐姐她想要的这个硬件层具体是什么，她只给我说了要向硬件这个方向靠了。我也比较懵。

**Comment by shejialuo** [comment]
目前已经构建好了初始框架，

#11: 操作系统与Linux部分，由雨馨和柏林负责。
#12：大语言模型，由陆毅负责。
#13: 故障检测，由天元负责。

Thanks all for proposals. This issue will be closed once above three are finished.

**Comment by shejialuo** [comment]
Thanks all. Close this issue.
